# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='username',
            field=models.CharField(default='anon_user', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
