# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-01 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_learner_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
