# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import elimika_backend.knowledge.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('base_category', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_categories', to='knowledge.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=elimika_backend.knowledge.models.img_directory_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_knowledges', to='knowledge.Category')),
            ],
        ),
    ]
